name: Validate JSON Resume Action
description: Validate a JSON resume.
author: Luke Weiler
branding:
  color: "green"
  icon: "package"
inputs:
  resume_path:
    description: The path to the resume.json file.
    required: true
runs:
  using: 'node16'
  main: 'index.js'
  args:
    - ${{ inputs.resume_path }}
